config/routes.rb
Kms::Engine.routes.draw do
  devise_for :kms_users,
    class_name: "Kms::User",
    failure_app:  'Kms::Devise::FailureApp',
    module: :devise,
    controllers: { registrations: "users/registrations" }
  constraints(format: "json") do
    resources :templates, format: true
    resources :snippets, except: [:new, :edit], format: true
    resources :pages, format: true do
      collection do
        post 'sorting'
      end
    end
    resources :assets, format: true, as: :kms_assets
    resources :users, only: [:index, :destroy], format: true
    resources :resources, only: :index, format: true
    resource :settings, only: [:show, :update], format: true
    get '/users/kms_user' => "users#kms_user", format: true
    post "/users/from_kms" => "users#create", format: true
  end
  post "/assets/ckeditor" => "assets#ckeditor"
  constraints(format: "html") do
    get "/(*path)" => "kms#index"
  end

end
Rails.application.routes.draw do
    root 'kms/public/pages#show'
    get "*path" => "kms/public/pages#show"
end

app/models/concerns/kms/compile_templates.rb
module Kms
  module CompileTemplates
    extend ActiveSupport::Concern

    included do
      validate :compiled_templates
      # on validation step object has no id,
      # that's why we need additional compile if validation pass
      after_commit :compile_templates, on: [:create, :update]
    end

    protected

    def compiled_templates
      Kms.template_manager.diagnostics.clear
      register_liquor_template
      return if Kms.template_manager.compile
      Kms.template_manager.errors.each do |error|
        splitted_error = error.message.split(':')
        errors.add(:content, [Kms.template_manager.decorate(error), splitted_error].flatten.join('<br>').gsub(/\s/, '&nbsp;'))
      end
    end

    def register_liquor_template
      if is_a?(Kms::Template)
        Kms.template_manager.register_layout(register_id, content, Kms::ExternalsRegistry.externals.keys)
      elsif is_a?(Kms::Page)
        Kms.template_manager.register_template(register_id, content, Kms::ExternalsRegistry.externals.keys)
      elsif is_a?(Kms::Snippet)
        Kms.template_manager.register_partial(register_id, content)
      end
    end

    def compile_templates
      register_liquor_template
      Kms.template_manager.compile
    end
  end
end

app/models/concerns/kms/permalinkable.rb
module Kms
  module Permalinkable
    extend ActiveSupport::Concern

    # Entity should respond to "slug"
    def permalink
      templatable_page = Kms::Page.where(templatable_type: self.class.name).first
      if templatable_page
        Pathname.new(templatable_page.parent.fullpath).join(self.slug.to_s).to_s
      end
    end
  end
end

app/models/concerns/kms/update_stylesheets_text.rb
module Kms
  module UpdateStylesheetsText
    extend ActiveSupport::Concern

    included do
      after_commit :restore_text, on: :create
    end

    protected

    def restore_text
      unless self.stylesheet_or_javascript?
        Asset.where("content_type like '%css%'").each do |asset|
          asset.store_text
          asset.save
        end
      end
    end
  end
end

app/models/kms/asset.rb
module Kms
  class Asset < ActiveRecord::Base
    include UpdateStylesheetsText

    mount_uploader :file, AssetUploader

    # заимствовано из Locomotive
    before_validation :store_text

    validate :unique_filename, on: :create

    attr_accessor :text, :performing_plain_text

    def filename
      read_attribute(:file)
    end

    def url
      file.url
    end

    def text
      @text ||= (file.read.force_encoding('UTF-8') rescue nil)
    end

    alias :content :text

    def performing_plain_text?
      performing_plain_text
    end

    def stylesheet_or_javascript?
      stylesheet? || javascript?
    end

    def stylesheet?
      content_type.include?("css")
    end

    def javascript?
      content_type.include?("javascript")
    end

    def store_text
      return if persisted? && !stylesheet_or_javascript?

      data = performing_plain_text? ? text : (file.present? ? file.read : nil)

      return if !stylesheet_or_javascript? || data.blank?

      sanitized_source = replace_urls(data)

      self.file = ::CarrierWave::SanitizedFile.new({
        tempfile: StringIO.new(sanitized_source),
        filename: filename || file.filename
      })

      @text = sanitized_source # no need to reset the plain_text instance variable to have the last version
    end

    protected

    def unique_filename
      if Asset.where(file: file.filename).exists?
        self.errors.add(:file, "is duplicate")
      end
    end

    def replace_urls(text)
      return if text.blank?

      text.gsub(/url\((.+)\)/) do |path|
        asset_name = $1.split("/")[-1]

        if asset = Asset.where(file: asset_name.gsub(/['"]/, '')).first
          "url(#{asset.file.url})"
        else
          path
        end
      end
    end
  end
end

app/models/kms/page.rb
module Kms
  class Page < ActiveRecord::Base
    include Liquor::Dropable
    include CompileTemplates

    INDEX_SLUG = "index"
    INDEX_FULLPATH = ""

    scope :published, lambda { where(published: true) }
    scope :listed, lambda { where(hidden: false) }
    scope :not_templatable, lambda { where(templatable: false) }

    belongs_to :template

    validates :slug, uniqueness: true, presence: true

    before_save :build_fullpath

    before_create :set_position

    has_ancestry

    def index?
      slug == INDEX_SLUG
    end

    def build_fullpath
      if index?
        self.fullpath = INDEX_FULLPATH # self.slug
      else
        slugs = (ancestors + [self]).map(&:slug)
        slugs.shift unless slugs.size == 1
        self.fullpath = File.join slugs.compact
      end
    end

    def set_position
      if parent.present?
        max = parent.children.maximum(:position)
      else
        max = Page.where('ancestry IS ?', nil).maximum(:position)
      end
      self.position = max ? max + 1 : 0
    end

    # fetch items for templatable page
    def fetch_items
      templatable_type.constantize.all
    end

    # fetch item by slug
    def fetch_item!(slug)
      return nil unless templatable?
      templatable_type.constantize.find_by_slug!(slug)
    end

    def register_id
      "#{self.class.name.parameterize("_")}_#{id}"
    end
  end
end

app/models/kms/settings.rb
module Kms
  class Settings < ActiveRecord::Base
    def self.instance
      first_or_create
    end
  end
end

app/models/kms/snippet.rb
module Kms
  class Snippet < ActiveRecord::Base
    include CompileTemplates

    validates :name, :slug, presence: true

    def register_id
      ['_', slug].join
    end
  end
end

app/models/kms/template.rb
module Kms
  class Template < ActiveRecord::Base
    include CompileTemplates

    validates :name, presence: true

    def register_id
      "#{self.class.name.parameterize("_")}_#{id}"
    end
  end
end

app/models/kms/user.rb
module Kms
  class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable

    ROLES = %i[admin content_manager]

    def admin?
      role == "admin"
    end

    def localized_role
      I18n.t("roles.#{role}")
    end
  end
end

app/controllers/kms/application_controller.rb
module Kms
  class ApplicationController < ActionController::Base
    before_action :authenticate_kms_user!
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    after_filter :set_csrf_cookie_for_ng

    def set_csrf_cookie_for_ng
      cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
    end

    protected

    def verified_request?
      super || cookies['XSRF-TOKEN'] == request.headers['X-XSRF-TOKEN']
    end

    def current_ability
      @current_ability ||= Ability.new(current_kms_user)
    end
  end
end

app/controllers/kms/assets_controller.rb
module Kms
  class AssetsController < ApplicationController
    load_and_authorize_resource
    skip_before_action :verify_authenticity_token, only: :ckeditor

    def index
      render json: Asset.all.to_json(methods: [:filename, :url])
    end

    def create
      @asset = Asset.new(asset_params)
      if @asset.save
        render json: {success: true, files: [@asset]}.to_json
      else
        render text: '', status: :unprocessable_entity
      end
    end

    def ckeditor
      @asset = Asset.new(file: params[:upload])
      if @asset.save
        render text: %Q"<script type='text/javascript'>
            window.parent.CKEDITOR.tools.callFunction(#{params[:CKEditorFuncNum]}, '#{@asset.file.url}');
          </script>"
      else
        render text: %Q"<script type='text/javascript'>
                window.parent.CKEDITOR.tools.callFunction(#{params[:CKEditorFuncNum]}, null, '#{@asset.errors.full_messages.first}');
              </script>"
      end
    end

    def update
      @asset = Asset.find(params[:id])
      asset_params.merge!(text: params[:text], performing_plain_text: params[:performing_plain_text]) if params[:text]
      @asset.update_attributes(asset_params)
      render json: @asset.to_json
    end

    def show
      @asset = Asset.find(params[:id])
      attrs = {}
      attrs.merge!(methods: [:text, :performing_plain_text]) if @asset.stylesheet_or_javascript?
      render json: @asset.to_json(attrs)
    end

    def destroy
      @asset = Asset.find(params[:id])
      @asset.destroy
      render json: @asset.to_json
    end

    protected

    def asset_params
      params.require(:asset).permit!
    end
  end
end

app/controllers/kms/kms_controller.rb
module Kms
  class KmsController < ApplicationController

    def index
      render "layouts/kms/kms"
    end
  end
end

app/controllers/kms/pages_controller.rb
module Kms
  class PagesController < ApplicationController
    load_and_authorize_resource
    wrap_parameters :page, include: [:title, :slug, :content, :published, :template_id, :templatable,:templatable_type,:position,:hidden, :parent_id]

    def index
      #render json: Page.order("created_at asc").to_json(methods: :parent_id, except: :ancestry)
      render json: Page.arrange_serializable(:order => :position).to_json
    end

    def create
      @page = Page.new(page_params)
      if @page.save
        render json: @page.to_json
      else
        render json: @page.to_json(except: :ancestry, methods: :errors), status: :unprocessable_entity
      end
    end

    def update
      @page = Page.find(params[:id])
      if @page.update_attributes(page_params)
        render json: @page.to_json
      else
        render json: @page.to_json(except: :ancestry, methods: :errors), status: :unprocessable_entity
      end
    end

    def show
      @page = Page.find(params[:id])
      render json: @page.to_json(methods: :parent_id, except: :ancestry)
    end

    def destroy
      @page = Page.find(params[:id])
      @page.destroy
      render json: @page.to_json
    end

    def sorting
      params["_json"].each_with_index do |page, index|
        p = Page.find_by_id(page["id"])
        p.update_attribute(:parent_id, nil)
        p.update_attribute(:position, index)
        sort(page["id"], page["children"]) if page["children"].present?
      end
      render json: Page.arrange_serializable.to_json
    end

    protected

    def sort(id, pages)
      pages.each_with_index do |page, index|
       p = Page.find_by_id(page["id"])
       p.update_attribute(:parent_id, id)
       p.update_attribute(:position, index)
       if page["children"].present?
         sort(page["id"], page["children"])
       end
      end
    end

    def page_params
      params.require(:page).permit!
    end
  end
end

app/controllers/kms/resources_controller.rb
module Kms
  class ResourcesController < ApplicationController
    authorize_resource :class => false

    def index
      render json: ResourceService.external_resources_hash.to_json
    end
  end
end

app/controllers/kms/settings_controller.rb
module Kms
  class SettingsController < ApplicationController
    authorize_resource :class => false

    def show
      render json: Settings.instance
    end

    def update
      @settings = Settings.instance
      if @settings.update_attributes(settings_params)
        render json: @settings
      else
        render json: @settings.to_json(methods: :errors), status: :unprocessable_entity
      end
    end

    protected

    def settings_params
      params.require(:setting).permit!
    end
  end
end

app/controllers/kms/snippets_controller.rb
module Kms
  class SnippetsController < ApplicationController
    respond_to :json

    def index
      respond_with Snippet.all, root: false
    end

    def create
      @snippet = Snippet.create(snippet_params)
      respond_with @snippet, root: false
    end

    def update
      @snippet = Snippet.find(params[:id])
      @snippet.update(snippet_params)
      respond_with @snippet, root: false
    end

    def show
      @snippet = Snippet.find(params[:id])
      respond_with @snippet, root: false
    end

    def destroy
      @snippet = Snippet.find(params[:id])
      @snippet.destroy
      respond_with @snippet
    end

    protected

    def snippet_params
      params.require(:snippet).permit!
    end
  end
end

app/controllers/kms/templates_controller.rb
module Kms
  class TemplatesController < ApplicationController
    load_and_authorize_resource
    def index
      render json: Template.all.to_json
    end

    def create
      @template = Template.new(template_params)
      if @template.save
        render json: @template.to_json
      else
        render json: @template.to_json(methods: :errors), status: :unprocessable_entity
      end
    end

    def update
      @template = Template.find(params[:id])
      if @template.update_attributes(template_params)
        render json: @template.to_json
      else
        render json: @template.to_json(methods: :errors), status: :unprocessable_entity
      end
    end

    def show
      @template = Template.find(params[:id])
      render json: @template.to_json
    end

    def destroy
      @template = Template.find(params[:id])
      @template.destroy
      render json: @template.to_json
    end

    protected

    def template_params
      params.require(:template).permit(:name,:content)
    end
  end
end

app/controllers/kms/users_controller.rb
module Kms
  class UsersController < ApplicationController
    before_action :authenticate_kms_user!
    load_and_authorize_resource
    skip_authorize_resource only: :kms_user

    def index
      render json: User.all.to_json(except: [:created_at, :updated_at], methods: :localized_role)
    end

    def create
      user_params.merge!(password: params[:password], password_confirmation: params[:password_confirmation]) if params[:password]
      @user = User.new(user_params)
      @user.save
      render json: @user.to_json
    end

    def destroy 
      @user = User.find(params[:id])
      @user.destroy
      render json: @user.to_json
    end

    def kms_user
      render json: current_kms_user.to_json
    end

    protected

    def user_params
      params.require(:user).permit!
    end


  end
end

app/helpers/kms/application_helper.rb
module Kms
  module ApplicationHelper
  end
end

app/views/layouts/kms/devise.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>KMS</title>

    <%= stylesheet_link_tag    'kms/application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Bootstrap core CSS -->

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

  <body>

    <div class="container">

      <%= yield %>

    </div> <!-- /container -->

</body></html>

app/views/layouts/kms/kms.html.erb
<!doctype html>
<html lang="en" ng-app="KMS">
<head>
	<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Kms</title>
  <%= stylesheet_link_tag    'kms/application', media: 'all', 'data-turbolinks-track' => true %>
  <script type="text/javascript">
     var CKEDITOR_BASEPATH = '/assets/ng-ckeditor/libs/ckeditor/';
   </script>
  <%= csrf_meta_tags %>

  <!-- build:js js/dashboard.js -->
  <!-- endbuild -->
  <!-- SCRIPTS -->
	<base href="/">

</head>
<body>
  <div id="page-wrapper" ng-controller="SidebarController" ng-class="{'active': toggle}" >

    <!-- Sidebar -->

    <div id="sidebar-wrapper">
      <ul class="sidebar">
        <li class="sidebar-main">
          <a href="#" ng-click="toggleSidebar()">
            Kms
            <span class="menu-icon glyphicon glyphicon-transfer"></span>
          </a>
        </li>
        <% Kms::ResourceService.resources.each do |group, resources| %>
          <% if resources.keys.any? {|r| can?(:index, r)} %>
            <li class="sidebar-title"><span><%= t(group) %></span></li>
          <% end %>
          <% resources.each do |resource_class, tab_icon_class| %>
            <% if can? :index, resource_class %>
              <li class="sidebar-list">
                <a ui-sref="<%= defined?(Kms::Model) && resource_class.is_a?(Kms::Model) ? "models.entries({modelId: #{resource_class.name}})" : resource_class.name.demodulize.tableize %>">
                  <%= resource_class.model_name.human(count: 1.1) %>
                  <span class="menu-icon fa <%= tab_icon_class %>"></span>
                </a>
              </li>
            <% end %>
          <% end %>
        <% end %>
      </ul>
      <div class="sidebar-footer">
        <div class="col-xs-4">
          <a href="http://webgradus.ru" target="_blank">
            &copy;Градус
          </a>
        </div>
        <div class="col-xs-4">
          <a ui-sref="help">
            <%= t(:help) %>
          </a>
        </div>
        <!--
        <div class="col-xs-4">
          <a href="#">
            Support
          </a>
        </div>
        -->
      </div>
    </div>

    <!-- End Sidebar -->

    <div id="content-wrapper">
      <div class="page-content">

        <!-- Header Bar -->

        <div class="row header">
          <div class="col-xs-12">
            <div class="user pull-right">
              <div class="item dropdown">
                <a href="#" class="dropdown-toggle">
                  <img src="<%= asset_path "Responsive-Dashboard/src/img/avatar.jpg" %>">
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                  <li class="dropdown-header">
                    <%= current_kms_user.try(:email) %>
                  </li>
                  <li class="divider"></li>
                  <li class="link">
                    <a ui-sref="settings">
                      <%= t(:settings) %>
                    </a>
                  </li>
                  <li class="link">
                    <%= link_to t(:sign_out), destroy_kms_user_session_path, target: "_self" %>
                  </li>
                </ul>
              </div>
              <!--
              <div class="item dropdown">
               <a href="#" class="dropdown-toggle">
                  <i class="fa fa-bell-o"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                  <li class="dropdown-header">
                    Notifications
                  </li>
                  <li class="divider"></li>
                  <li>
                    <a href="#">Server Down!</a>
                  </li>
                </ul>
              </div>
              -->
            </div>
            <div class="meta">
              <div class="page" ui-view="header">
                Dashboard
              </div>
              <!--
              <div class="breadcrumb-links">
                Home / Dashboard
              </div>-->
            </div>
          </div>
        </div>

        <!-- End Header Bar -->

        <!-- Main Content -->
        <section ui-view></section>
      </div><!-- End Page Content -->
    </div><!-- End Content Wrapper -->
  </div><!-- End Page Wrapper -->

  <%= javascript_include_tag 'kms/application', 'data-turbolinks-track' => true %>

</body>
</html>